controller_list:
  - name: mico_arm
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - mico_joint_1
      - mico_joint_2
      - mico_joint_3
      - mico_joint_4
      - mico_joint_5
      - mico_joint_6      

