#!/bin/bash
echo Deleting bag files...
find . -name "*.bag" -type f -delete
echo Deleting csv files...
find . -name "*.csv" -type f -delete
echo Deleting pcd files...
find . -name "*.pcd" -type f -delete
echo Deleting jpg files...
find . -name "*.jpg" -type f -delete
echo Deleting ini files...
find . -name "*.ini" -type f -delete
echo Delete completed.
